spring:
  application:
    name: EurekaFeignClient
  cloud:
    discovery:
      enabled: true


server:
  port: 8082


eureka:
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}